"""Updated user nullable fields

Revision ID: b606927785ca
Revises: b62578d1f099
Create Date: 2023-11-13 16:30:38.358910+04:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b606927785ca'
down_revision: Union[str, None] = 'b62578d1f099'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'city',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'country',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::real"))
    # ### end Alembic commands ###
